name: Java CI with Maven

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - "**/README.md"
      - "**/CONTRIBUTING.md"
      - "**/CONTRIBUTORS.txt"
      - '**/CODE_OF_CONDUCT.md'
      - "**/LICENSE"
      - "**/CODEOWNERS"
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - "**/README.md"
      - "**/CONTRIBUTING.md"
      - "**/CONTRIBUTORS.txt"
      - '**/CODE_OF_CONDUCT.md'
      - "**/LICENSE"
      - "**/CODEOWNERS"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11, 17, 21 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "corretto"
          cache: "maven"
          check-latest: true

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compile with Maven
        run: mvn -T 1C clean generate-sources compile --file pom.xml

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11, 17, 21 ]
    needs:
        - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "corretto"
          cache: "maven"
          check-latest: true

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Test with Maven
        run: mvn -T 1C test-compile test --file pom.xml
